mappings:
  XMLGoogleShoppingFeedController: Sunnysideup\EcommerceGoogleShoppingFeed\Controllers\XMLGoogleShoppingFeedController
  GoogleShoppingFeedController: Sunnysideup\EcommerceGoogleShoppingFeed\Controllers\GoogleShoppingFeedController
  TSVGoogleShoppingFeedController: Sunnysideup\EcommerceGoogleShoppingFeed\Controllers\TSVGoogleShoppingFeedController
  GoogleShoppingFeedExtension: Sunnysideup\EcommerceGoogleShoppingFeed\Extensions\GoogleShoppingFeedExtension
  ProductCollectionForGoogleShoppingFeed: Sunnysideup\EcommerceGoogleShoppingFeed\Api\ProductCollectionForGoogleShoppingFeed
  GoogleProductCategory: Sunnysideup\EcommerceGoogleShoppingFeed\Model\GoogleProductCategory
