---
Name: googleshoppingfeedroutes
---
SilverStripe\Control\Director:
  rules:
    shoppingfeed.xml: Sunnysideup\EcommerceGoogleShoppingFeed\Controllers\XMLGoogleShoppingFeedController
    shoppingfeed.txt: Sunnysideup\EcommerceGoogleShoppingFeed\Controllers\TSVGoogleShoppingFeedController
